<form role="form" action="<?= $this->action ?>" method="POST">

  <div class="form-group <?= $this->room->errors('name') ? 'has-error' : '' ?>">
    <label class="control-label" for="room_name">Nome:*</label>
    <input type="text" class="form-control" name="room[name]" value="<?= $this->room->getName() ?>"
           id="room_name" placeholder="Seu nome">
    <p class="help-block"><?= $this->room->errors('name') ?></p>
  </div>

  <div class="form-group <?= $this->room->errors('price') ? 'has-error' : '' ?>">
    <label class="control-label" for="room_price">Preço:*</label>
    <input type="text" class="form-control" name="room[price]" value="<?= $this->room->getPrice() ?>"
           id="room_price" placeholder="Preço do quarto">
    <p class="help-block"><?= $this->room->errors('price') ?></p>
  </div>

  <div class="form-group <?= $this->room->errors('category_id') ? 'has-error' : '' ?>" >
    <label class='control-label' for='room_category_id'>Categoria *</label>
    <select name='room[category_id]'>
      <option value=''>Selecione uma categoria</option>
      <?php foreach($this->categories as $category) {?>
         <option value='<?= $category->getId() ?>'
            <?= ($category->getId() === $this->room->getCategoryId()) ? 'selected' : '' ?> >
            <?= $category->getName() ?>
         </option>
      <?php } ?>
    </select>
    <span class='help-inline'><?= $this->room->errors('category_id')?></span>
  </div>


  <button type="submit" class="btn btn-primary"> <?= $this->submit ?></button>
</form>
