<section>
  <header class='page-header'>
    <div class='clearfix'>
      <div class='pull-left'>
        <h3> Usuário <?= $this->user->getName(); ?> </h3>
        <small class='help-block'>Cadastrado em <?= $this->user->getCreatedAt() ?></small>
      </div>
      <div class='pull-right'>
        <?= link_to("/admin/usuarios/{$this->user->getId()}/editar",'Editar')?> |
        <?= link_to('/admin/usuarios', 'Todos usuários')?>
      </div>
    </div>
  </header>

  <article>
    <p><strong>Email: </strong><?= $this->user->getEmail() ?></p>
  </article>
</section>
